version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        PHP_VERSION: php:8.2-apache
        MAGENTO_PUBLIC_KEY: ${MAGENTO_PUBLIC_KEY}
        MAGENTO_SECRET_KEY: ${MAGENTO_SECRET_KEY}
    ports:
      - "9999:80"
    volumes:
      - ./src:/var/www/html/app/code/${VENDOR_NAME:-SEEC}/${MODULE_NAME:-MagentoTestModule}
      - ./ecs.php:/var/www/html/ecs.php
      - ./phpstan.neon:/var/www/html/phpstan.neon
      - ./magento:/var/www/html/vendor/magento-ext
      - ./docker/php/etc/generate-module-with-mage2gen.sh:/usr/local/bin/mage2gen-module-creator
    environment:
      PHP_IDE_CONFIG: serverName=magento2-behat-extension
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env

  mysql:
    image: mariadb:10.6
    environment:
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: magento
    volumes:
      - ./docker/data/database/:/var/lib/mysql/
    ports:
      - "9906:3306"

  opensearch:
    image: opensearchproject/opensearch:2.7.0
    environment:
      discovery.type: single-node
      cluster.name: opensearch-cluster
      node.name: opensearch-node
      bootstrap.memory_lock: true
      OPENSEARCH_JAVA_OPTS: -Xms512m -Xmx512m
      DISABLE_INSTALL_DEMO_CONFIG: true
      DISABLE_SECURITY_PLUGIN: true
    ports:
      - "8892:9200"

volumes:
  magento:

